package CalculadoraFuncional;

public class ParteVisualCalculadora extends javax.swing.JFrame {
    
    int num1,num2;
    String signo;
    
    public ParteVisualCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonSeis = new javax.swing.JButton();
        BotonTres = new javax.swing.JButton();
        BotonMultiplicacion = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonSiete = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonCuatro = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonUno = new javax.swing.JButton();
        BotonCero = new javax.swing.JButton();
        BotonOcho = new javax.swing.JButton();
        BotonCinco = new javax.swing.JButton();
        BotonDos = new javax.swing.JButton();
        BotonNueve = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        MostrarNumeros = new javax.swing.JLabel();
        BotonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BotonSeis.setBackground(new java.awt.Color(153, 153, 153));
        BotonSeis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonSeis.setForeground(new java.awt.Color(255, 255, 255));
        BotonSeis.setText("6");
        BotonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeisActionPerformed(evt);
            }
        });

        BotonTres.setBackground(new java.awt.Color(153, 153, 153));
        BotonTres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonTres.setForeground(new java.awt.Color(255, 255, 255));
        BotonTres.setText("3");
        BotonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTresActionPerformed(evt);
            }
        });

        BotonMultiplicacion.setBackground(new java.awt.Color(255, 204, 0));
        BotonMultiplicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonMultiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        BotonMultiplicacion.setText("x");
        BotonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicacionActionPerformed(evt);
            }
        });

        BotonResta.setBackground(new java.awt.Color(255, 204, 0));
        BotonResta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonResta.setForeground(new java.awt.Color(255, 255, 255));
        BotonResta.setText("-");
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });

        BotonSiete.setBackground(new java.awt.Color(153, 153, 153));
        BotonSiete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonSiete.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiete.setText("7");
        BotonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSieteActionPerformed(evt);
            }
        });

        BotonSuma.setBackground(new java.awt.Color(255, 204, 0));
        BotonSuma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonSuma.setForeground(new java.awt.Color(255, 255, 255));
        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });

        BotonCuatro.setBackground(new java.awt.Color(153, 153, 153));
        BotonCuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonCuatro.setForeground(new java.awt.Color(255, 255, 255));
        BotonCuatro.setText("4");
        BotonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCuatroActionPerformed(evt);
            }
        });

        BotonIgual.setBackground(new java.awt.Color(255, 204, 0));
        BotonIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });

        BotonUno.setBackground(new java.awt.Color(153, 153, 153));
        BotonUno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonUno.setForeground(new java.awt.Color(255, 255, 255));
        BotonUno.setText("1");
        BotonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnoActionPerformed(evt);
            }
        });

        BotonCero.setBackground(new java.awt.Color(153, 153, 153));
        BotonCero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonCero.setForeground(new java.awt.Color(255, 255, 255));
        BotonCero.setText("0");
        BotonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCeroActionPerformed(evt);
            }
        });

        BotonOcho.setBackground(new java.awt.Color(153, 153, 153));
        BotonOcho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonOcho.setForeground(new java.awt.Color(255, 255, 255));
        BotonOcho.setText("8");
        BotonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOchoActionPerformed(evt);
            }
        });

        BotonCinco.setBackground(new java.awt.Color(153, 153, 153));
        BotonCinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonCinco.setForeground(new java.awt.Color(255, 255, 255));
        BotonCinco.setText("5");
        BotonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCincoActionPerformed(evt);
            }
        });

        BotonDos.setBackground(new java.awt.Color(153, 153, 153));
        BotonDos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonDos.setForeground(new java.awt.Color(255, 255, 255));
        BotonDos.setText("2");
        BotonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDosActionPerformed(evt);
            }
        });

        BotonNueve.setBackground(new java.awt.Color(153, 153, 153));
        BotonNueve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonNueve.setForeground(new java.awt.Color(255, 255, 255));
        BotonNueve.setText("9");
        BotonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNueveActionPerformed(evt);
            }
        });

        BotonDivision.setBackground(new java.awt.Color(255, 204, 0));
        BotonDivision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonDivision.setForeground(new java.awt.Color(255, 255, 255));
        BotonDivision.setText("/");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });

        MostrarNumeros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MostrarNumeros.setForeground(new java.awt.Color(255, 255, 255));
        MostrarNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        BotonBorrar.setBackground(new java.awt.Color(204, 204, 204));
        BotonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("C");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BotonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BotonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(BotonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BotonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BotonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(BotonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MostrarNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(MostrarNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCeroActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"0");
    }//GEN-LAST:event_BotonCeroActionPerformed

    private void BotonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnoActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"1");
    }//GEN-LAST:event_BotonUnoActionPerformed

    private void BotonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDosActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"2");
    }//GEN-LAST:event_BotonDosActionPerformed

    private void BotonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTresActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"3");
    }//GEN-LAST:event_BotonTresActionPerformed

    private void BotonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCuatroActionPerformed
        // TODO add your handling code here:
        MostrarNumeros.setText(MostrarNumeros.getText()+"4");
    }//GEN-LAST:event_BotonCuatroActionPerformed

    private void BotonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCincoActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"5");
    }//GEN-LAST:event_BotonCincoActionPerformed

    private void BotonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeisActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"6");
    }//GEN-LAST:event_BotonSeisActionPerformed

    private void BotonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSieteActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"7");
    }//GEN-LAST:event_BotonSieteActionPerformed

    private void BotonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOchoActionPerformed
        MostrarNumeros.setText(MostrarNumeros.getText()+"8");
    }//GEN-LAST:event_BotonOchoActionPerformed

    private void BotonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNueveActionPerformed
MostrarNumeros.setText(MostrarNumeros.getText()+"9");
    }//GEN-LAST:event_BotonNueveActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        MostrarNumeros.setText("");
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        num1 = Integer.parseInt(MostrarNumeros.getText());
        signo = "/";
        MostrarNumeros.setText("");
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicacionActionPerformed
        num1 = Integer.parseInt(MostrarNumeros.getText());
        signo = "*";
        MostrarNumeros.setText("");
    }//GEN-LAST:event_BotonMultiplicacionActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        num1 = Integer.parseInt(MostrarNumeros.getText());
        signo = "-";
        MostrarNumeros.setText("");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        num1 = Integer.parseInt(MostrarNumeros.getText());
        signo = "+";
        MostrarNumeros.setText("");
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        num2 = Integer.parseInt(MostrarNumeros.getText());
        
        switch(signo){
            case "+": MostrarNumeros.setText(Integer.toString(num1+num2)); break;
            case "-": MostrarNumeros.setText(Integer.toString(num1-num2)); break;
            case "*": MostrarNumeros.setText(Integer.toString(num1*num2)); break;
            case "/": MostrarNumeros.setText(Integer.toString(num1/num2)); break;
        }
    }//GEN-LAST:event_BotonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParteVisualCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParteVisualCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParteVisualCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParteVisualCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParteVisualCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonCero;
    private javax.swing.JButton BotonCinco;
    private javax.swing.JButton BotonCuatro;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonDos;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMultiplicacion;
    private javax.swing.JButton BotonNueve;
    private javax.swing.JButton BotonOcho;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSeis;
    private javax.swing.JButton BotonSiete;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton BotonTres;
    private javax.swing.JButton BotonUno;
    private javax.swing.JLabel MostrarNumeros;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
